// Story Mode persisted-question (de)serialization proof (WAVE 3b).
//
// WAVE 3b wires the code-authoritative question-architecture BANK into the live controller: Story
// Mode now serves questions GENERATED by the bank (deterministic, code-graded) instead of reusing
// bundled lesson steps. The controller is a React hook with no DOM test harness, so the pure
// `ThemedQuestion <-> LessonStep` seam it relies on (`src/story/rehydrateQuestion.ts`) is extracted
// and proven here. These tests show, without any LLM:
//   - a served architecture question PERSISTS its id + paramSeed (never an answer key, never a
//     variantSeed) and REHYDRATES to the exact canonical step whose CODE-computed key grades it;
//   - the rebuild is deterministic for a fixed id+seed (resume safety) and tolerates a missing seed;
//   - a themed (story-wrapped) question rehydrates with the saved DISPLAY text but the same code key,
//     while a numerically-incoherent or id-mismatched saved theme degrades to the canonical step;
//   - the anti-repeat key is `arch:<id>` for bank questions and `${lessonId}:${stepId}` for legacy;
//   - an unknown architecture id (or bundled step) rehydrates to null (a stale question); and
//   - LEGACY already-saved lesson-reuse questions still rehydrate unchanged (back-compat).

import assert from 'node:assert/strict'
import { test } from 'node:test'

import { oneStepEquationsLesson } from '../src/domain'
import type { LessonStep, ThemedQuestion } from '../src/domain'
import {
  ARCHITECTURE_CATALOG,
  architectureKey,
  checkInputStep,
  checkOperationChoiceStep,
  checkSequenceStep,
  generateForArchitecture,
  mulberry32,
  randomizeQuestionNumbers,
} from '../src/engine'
import { applyRetheme } from '../src/story/applyRetheme'
import { questionKey, rehydrateQuestion, toThemedQuestion } from '../src/story/rehydrateQuestion'
import { findStep } from './helpers/findStep'

const ISO = '2026-06-25T00:00:00.000Z'

// Grade a (rehydrated) step with the REAL checker for its type, proving the key is code-computed.
const gradeCorrect = (step: LessonStep, answer: string | string[]): boolean => {
  if (step.type === 'input') return checkInputStep(step, answer as string).correct
  if (step.type === 'sequence') return checkSequenceStep(step, answer as string[]).correct
  if (step.type === 'operation-choice') return checkOperationChoiceStep(step, answer as string).correct
  throw new Error(`no grader wired for step type ${step.type}`)
}

// A wrong answer must still be REJECTED by the rehydrated step's code key (no false positives).
// The garbage form is type-aware (each grader expects the shape its step type uses).
const assertWrongRejected = (step: LessonStep, answer: string | string[]): void => {
  if (step.type === 'input') {
    assert.equal(checkInputStep(step, 'definitely-not-a-valid-answer').correct, false)
    const numeric = Number(answer)
    if (Number.isFinite(numeric)) {
      assert.equal(checkInputStep(step, String(numeric + 1)).correct, false, 'a near miss must grade false')
    }
  } else if (step.type === 'sequence') {
    assert.equal(checkSequenceStep(step, ['not-a-real-tile']).correct, false)
    const order = answer as string[]
    if (order.length > 1) {
      assert.equal(checkSequenceStep(step, [...order].reverse()).correct, false, 'a wrong order must grade false')
    }
  } else if (step.type === 'operation-choice') {
    assert.equal(checkOperationChoiceStep(step, 'not-a-real-option').correct, false)
    const wrong = step.choices.find((choice) => choice.id !== (answer as string))
    if (wrong) assert.equal(checkOperationChoiceStep(step, wrong.id).correct, false, 'a wrong option must grade false')
  }
}

// --- questionKey: the anti-repeat / persisted-identity key per lineage --------------------------

test('questionKey returns the bank `arch:<id>` key for an architecture question', () => {
  const arch = ARCHITECTURE_CATALOG[0]
  const question = toThemedQuestion(arch, generateForArchitecture(arch.id, 1)!.step, false, 1, ISO)
  assert.equal(questionKey(question), architectureKey(arch.id))
  assert.equal(questionKey(question), `arch:${arch.id}`)
})

test('questionKey keeps the legacy `${lessonId}:${stepId}` form for a lesson-reuse question', () => {
  const legacy: ThemedQuestion = {
    sourceLessonId: 'one-step-equations',
    sourceStepId: 'input-three-x',
    stepType: 'input',
    themedPrompt: 'Solve 3x = 12.',
    themed: false,
    generatedAt: ISO,
  }
  assert.equal(questionKey(legacy), 'one-step-equations:input-three-x')
})

// --- toThemedQuestion: what an architecture question persists ----------------------------------

test('toThemedQuestion persists architecture identity + paramSeed and never a variantSeed', () => {
  const arch = ARCHITECTURE_CATALOG[0]
  const { step } = generateForArchitecture(arch.id, 42)!
  const question = toThemedQuestion(arch, step, false, 42, ISO)

  assert.equal(question.architectureId, arch.id)
  assert.equal(question.paramSeed, 42)
  assert.equal(question.sourceLessonId, arch.requiredLessonId)
  assert.equal(question.sourceStepId, architectureKey(arch.id))
  assert.equal(question.stepType, step.type)
  assert.equal(question.generatedAt, ISO)
  // Architecture questions are rebuilt from paramSeed, never the legacy number-variant seed.
  assert.equal('variantSeed' in question, false)
})

// --- Architecture round-trip: persist -> rehydrate rebuilds the SAME code-graded step ----------

for (const arch of ARCHITECTURE_CATALOG) {
  test(`architecture round-trips to a deterministic, code-graded canonical step: ${arch.id}`, () => {
    for (let seed = 0; seed < 40; seed += 1) {
      const generated = generateForArchitecture(arch.id, seed)
      assert.ok(generated, `architecture ${arch.id} must generate for seed ${seed}`)

      // The "AI was unavailable / re-theme failed" path: themed=false, persist the canonical step.
      const persisted = toThemedQuestion(arch, generated.step, false, seed, ISO)
      const rebuilt = rehydrateQuestion(persisted)
      assert.ok(rebuilt, 'a persisted architecture question must rehydrate')
      assert.equal(rebuilt.themed, false)
      // Deterministic rebuild: the rehydrated step equals a fresh generation for the same seed, so a
      // refresh shows the identical question — and the answer key is recomputed by CODE, not stored.
      assert.deepEqual(rebuilt.step, generated.step)
      assert.equal(rebuilt.step.type, arch.stepType)
      assert.equal(gradeCorrect(rebuilt.step, generated.answer), true)
      assertWrongRejected(rebuilt.step, generated.answer)
    }
  })
}

test('a fixed architectureId + paramSeed always rehydrates to a deep-equal step (resume safety)', () => {
  for (const arch of ARCHITECTURE_CATALOG) {
    for (const seed of [0, 5, 4242, 0xbeef]) {
      const persisted = toThemedQuestion(arch, generateForArchitecture(arch.id, seed)!.step, false, seed, ISO)
      assert.deepEqual(rehydrateQuestion(persisted), rehydrateQuestion(persisted))
    }
  }
})

test('a missing paramSeed rebuilds deterministically with seed 0', () => {
  const arch = ARCHITECTURE_CATALOG[0]
  const persisted: ThemedQuestion = {
    architectureId: arch.id,
    sourceLessonId: arch.requiredLessonId,
    sourceStepId: architectureKey(arch.id),
    stepType: arch.stepType,
    themedPrompt: 'Solve it.',
    themed: false,
    generatedAt: ISO,
  }
  const rebuilt = rehydrateQuestion(persisted)
  assert.ok(rebuilt)
  assert.deepEqual(rebuilt.step, generateForArchitecture(arch.id, 0)!.step)
})

// --- Themed (story-wrapped) overlay: saved display text, code answer key -----------------------

test('a themed architecture question rehydrates with the saved story text but the code key', () => {
  const arch = ARCHITECTURE_CATALOG.find((entry) => entry.stepType === 'input')!
  const generated = generateForArchitecture(arch.id, 7)!
  const equationText = 'equation' in generated.step ? generated.step.equation : ''
  // A coherent re-theme: a story wrapper that still states the SAME equation (numbers unchanged).
  const themedPrompt = `Captain Vega recalibrates the reactor: solve ${equationText} to vent the core.`
  const themedStep = applyRetheme(generated.step, { themedPrompt }).step
  const persisted = toThemedQuestion(arch, themedStep, true, 7, ISO)
  assert.equal(persisted.themed, true)

  const rebuilt = rehydrateQuestion(persisted)
  assert.ok(rebuilt)
  assert.equal(rebuilt.themed, true)
  assert.equal('prompt' in rebuilt.step ? rebuilt.step.prompt : '', themedPrompt)
  // The themed surface text changed, but the canonical answer key still grades correctly.
  assert.equal(gradeCorrect(rebuilt.step, generated.answer), true)
  assertWrongRejected(rebuilt.step, generated.answer)
})

test('a numerically-incoherent saved theme degrades to the canonical step on resume', () => {
  const arch = ARCHITECTURE_CATALOG.find((entry) => entry.stepType === 'input')!
  const generated = generateForArchitecture(arch.id, 11)!
  // A saved theme whose prompt states a DIFFERENT equation (changed numbers) must be rejected by the
  // coherence guard so the question/equation/answer can never disagree after resume.
  const persisted: ThemedQuestion = {
    ...toThemedQuestion(arch, generated.step, true, 11, ISO),
    themedPrompt: 'Solve for x: x + 999 = 1000000',
  }
  const rebuilt = rehydrateQuestion(persisted)
  assert.ok(rebuilt)
  assert.equal(rebuilt.themed, false, 'an incoherent theme must fall back to un-themed')
  assert.deepEqual(rebuilt.step, generated.step)
  assert.equal(gradeCorrect(rebuilt.step, generated.answer), true)
})

test('a themed question whose ids no longer match the source falls back to the canonical step', () => {
  const arch = ARCHITECTURE_CATALOG.find((entry) => entry.stepType === 'sequence')!
  const generated = generateForArchitecture(arch.id, 3)!
  // applyRetheme requires the themed id-set to EXACTLY equal the source; a foreign id set is dropped.
  const persisted: ThemedQuestion = {
    ...toThemedQuestion(arch, generated.step, true, 3, ISO),
    themedPrompt: 'Put the steps in order.',
    themedTiles: [{ id: 'not-a-real-tile-id', label: 'nope' }],
  }
  const rebuilt = rehydrateQuestion(persisted)
  assert.ok(rebuilt)
  assert.equal(rebuilt.themed, false)
  assert.deepEqual(rebuilt.step, generated.step)
  assert.equal(gradeCorrect(rebuilt.step, generated.answer), true)
})

test('an unknown architecture id rehydrates to null (a stale question)', () => {
  const persisted: ThemedQuestion = {
    architectureId: 'architecture-that-does-not-exist',
    paramSeed: 1,
    sourceLessonId: 'one-step-equations',
    sourceStepId: 'arch:architecture-that-does-not-exist',
    stepType: 'input',
    themedPrompt: 'Solve it.',
    themed: false,
    generatedAt: ISO,
  }
  assert.equal(rehydrateQuestion(persisted), null)
})

// --- LEGACY back-compat: already-saved lesson-reuse questions still rehydrate ------------------

test('LEGACY: a lesson-reuse question rebuilds its number variant from the bundled step + seed', () => {
  const original = findStep(oneStepEquationsLesson, 'input-three-x', 'input') // 3x = 12
  for (const seed of [1, 7, 99]) {
    const legacy: ThemedQuestion = {
      sourceLessonId: 'one-step-equations',
      sourceStepId: 'input-three-x',
      stepType: 'input',
      themedPrompt: original.prompt,
      themed: false,
      variantSeed: seed,
      generatedAt: ISO,
    }
    const rebuilt = rehydrateQuestion(legacy)
    assert.ok(rebuilt)
    assert.equal(rebuilt.themed, false)
    // The legacy path is UNCHANGED: rebuild via lesson lookup + the same number-variation engine.
    assert.deepEqual(rebuilt.step, randomizeQuestionNumbers(original, mulberry32(seed)))
    const variant = rebuilt.step as Extract<LessonStep, { type: 'input' }>
    const solution = variant.accept.map(Number).find((value) => Number.isInteger(value))!
    assert.equal(checkInputStep(variant, String(solution)).correct, true)
    assert.equal(checkInputStep(variant, String(solution + 1)).correct, false)
  }
})

test('LEGACY: a question with no variantSeed rebuilds the original bundled numbers verbatim', () => {
  const original = findStep(oneStepEquationsLesson, 'input-three-x', 'input')
  const legacy: ThemedQuestion = {
    sourceLessonId: 'one-step-equations',
    sourceStepId: 'input-three-x',
    stepType: 'input',
    themedPrompt: original.prompt,
    themed: false,
    generatedAt: ISO,
  }
  const rebuilt = rehydrateQuestion(legacy)
  assert.ok(rebuilt)
  assert.deepEqual(rebuilt.step, original)
})

test('LEGACY: a themed lesson question overlays its saved text onto the rebuilt variant', () => {
  // `input-three-x` is the bundled `3x = 12`; with no variantSeed it rebuilds those exact numbers.
  const legacy: ThemedQuestion = {
    sourceLessonId: 'one-step-equations',
    sourceStepId: 'input-three-x',
    stepType: 'input',
    // Coherent story wrapper that still states the bundled equation (no variantSeed -> 3x = 12).
    themedPrompt: 'The vault gate shows 3x = 12 — solve for x to open it.',
    themed: true,
    generatedAt: ISO,
  }
  const rebuilt = rehydrateQuestion(legacy)
  assert.ok(rebuilt)
  assert.equal(rebuilt.themed, true)
  assert.match('prompt' in rebuilt.step ? rebuilt.step.prompt : '', /vault gate/)
  const variant = rebuilt.step as Extract<LessonStep, { type: 'input' }>
  assert.equal(checkInputStep(variant, '4').correct, true) // 3x = 12 -> x = 4
})

test('LEGACY: an unknown bundled step id rehydrates to null (a stale question)', () => {
  const legacy: ThemedQuestion = {
    sourceLessonId: 'one-step-equations',
    sourceStepId: 'a-step-that-was-removed',
    stepType: 'input',
    themedPrompt: 'Solve it.',
    themed: false,
    generatedAt: ISO,
  }
  assert.equal(rehydrateQuestion(legacy), null)
})
